version: '3'

services:
  app:
    build: .
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    links:
      - redis
    ports:
      - 8080:8080
    networks:
      - network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demodb
    ports:
      - 3306:3306
    networks:
      - network
    volumes:
      - ~/java/springboot/data/mysql-data:/var/lib/mysql
  
  redis:
    image: redis:v1
    container_name: redis
    build: ./redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    external: true